"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@32fo9mfavjh$vl96qu#ctqi(_j#jt*s%rb7-6^gyhg74ga3od'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '192.168.1.5',
    '127.0.0.1',
]


# Application definition

INSTALLED_APPS = [
    'users',
    'bloging.apps.BlogingConfig',
    'crispy_forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

CRISPY_TEMPLATE_PACK='bootstrap4'

#login form in django direct users by diffult to account/profile , but we dont want to do that 
#we want to direct them to the home page of the blog
LOGIN_REDIRECT_URL='blog_home'

#login_required redirection if user not loged in to the login page ,but we need to specify the login page

LOGIN_URL='login'   

"""
*pic file get created in same level as our apps ,if we have multiple app use pic or media multiple files will
get created 
*note:pic doesnot get stored in the db for performance resoncs ,they stored in the file system.
*media root is the directory where the uploaded file will get saved.
*BASE_DIR var django created in line 17 that have the path to our project base directory , so what that say is 
we make file called media in the base directory of that project and that the media root .
*media_url:is the public url (how to access the media file in the browser)
so now when when we have any media of any app it will get stored at media directory 
e.x for users we specifie profile_pics dic that will be inside the media ,url to get there is the 
/media/profile_pics/(name of the pic)
"""
MEDIA_ROOT=os.path.join(BASE_DIR,'media')
MEDIA_URL='/media/'


EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='smtp.gmail.com' 
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER='abdelrhman.bedo007@gmail.com'
EMAIL_HOST_PASSWORD='acqs sfia qaxm hbzk'
DEFAULT_FROM_EMAIL='elshe2 bemse'

#AUTH_USER_MODEL="users.CustomUser"